### ISSUE TITLE
Add timers between states

### ISSUE THREAD

**Issue by arcostasi** [jagarsoft/php-state-machine#5]
Very interesting your library, I took the liberty of doing some tests and sharing on my GitHub.

**Suggestion:**
Let's assume that our state machine uses timers to indicate when to change state. Each state is associated with a timer, and when the timer expires, the state changes.

See my example using your library, I tried to add the timer inside the closure.
https://github.com/arcostasi/php-fsm

I think this delay cannot be blocked with the use of Sleep, but it was just an implementation idea for a semaphore.

**Comment by jagarsoft** [comment]
It sounds great!!
Give me time to have a look... ;-)

**Comment by jagarsoft** [comment]
Hi again!

I sent you a pull request!

Please, have a look ;-)

PS: Keep in touch!

**Comment by jagarsoft** [comment]
Pull request was merged!!

https://github.com/arcostasi/php-fsm/commit/5f8cf3cbf3bf0a1f16ea4d46ae8d54dd33d7b935
